name: cpp-check

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential cppcheck curl python python-pygments

      - run: cppcheck --xml --xml-version=2 "modules/core/src" 2> cppcheck.xml
      - run: cppcheck-htmlreport --file=cppcheck.xml --title=cppcheck --report-dir=./public

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: archive cppcheck.xml
        uses: actions/upload-artifact@v1
        with:
            name: cppcheck.xml
            path: cppcheck.xml