name: cpp-check

on:
  push:
    
jobs:
  cppcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: printenv
        run: env

      - name: setup
        id: setup
        run: |
              sudo apt-get update
              sudo apt-get install -y build-essential cppcheck curl python python-pygments

      - name: checkout
        if: steps.setup.conclusion == 'success'
        uses: actions/checkout@v2

      - name: cppcheck
        if: steps.setup.conclusion == 'success'
        id: cppcheck
        run: |
              cppcheck --xml --xml-version=2 "modules/core/src" 2> cppcheck.xml
              cppcheck-htmlreport --file=cppcheck.xml --title=cppcheck --report-dir=./public

      - name: archive-cppcheck.xml
        if: steps.cppcheck.conclusion == 'success'
        uses: actions/upload-artifact@v1
        with:
            name: cppcheck.xml
            path: cppcheck.xml

      - name: archive-html-report
        if: steps.cppcheck.conclusion == 'success'
        uses: actions/upload-artifact@v1
        with:
            name: html-report
            path: public
